export { default as PrevArrow } from './PrevArrow.svg';
export { default as NextArrow } from './NextArrow.svg';
export { default as Confirm } from './Confirm.svg';
export { default as Warning } from './Warning.svg';
export { default as Error } from './Error.svg';
export { default as PersonIcon } from './PersonIcon.svg';
export { default as CartBox } from './CartBox.svg';
export { default as CartBoxConfirm } from './CartBoxConfirm.svg';
export { default as DefaultAvatar } from './DefaultAvatar.svg';
